### ISSUE TITLE
Segmentation fault when running the node

### ISSUE THREAD

**Issue by TheRobotStudio** [firephinx/openpose_ros#1]
Hello,
Thanks for developing an openpose wrapper for ROS!
I'm using Ubuntu 16.04 with ROS Kinetic. The OpenPose package is installed and examples are working.
After install and build of your packages and the dependencies successfully, I ran the node using a launch file with GDB option and I got a segmentation fault.
The image topic is produced by usb_cam package using a 1280*720 image from a logitech HD 720p webcam, and the usb_cam node is executed first:
```
(gdb) run
Starting program: /home/cyril/catkin_ws/devel/lib/openpose_ros/openpose_ros_node_with_face_and_hands __name:=openpose_node __log:=/home/cyril/.ros/log/c46b30d6-6def-11e7-8639-38d547137ed4/openpose_node-1.log
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffc815a700 (LWP 14222)]
OpenPose ROS Node with Face and Hands
[New Thread 0x7fffc0d24700 (LWP 14225)]
Auto-detecting GPUs... Detected 1 GPU(s), using them all.
Starting thread(s)
[New Thread 0x7fffc0209700 (LWP 14226)]
[New Thread 0x7fffbfa08700 (LWP 14227)]
[New Thread 0x7fffbf207700 (LWP 14228)]
[New Thread 0x7fffbe671700 (LWP 14229)]
[New Thread 0x7fffbde70700 (LWP 14231)]
[New Thread 0x7fffbd66f700 (LWP 14232)]
[New Thread 0x7fffbce6e700 (LWP 14233)]
[New Thread 0x7fffa7fff700 (LWP 14238)]
[New Thread 0x7fffa77fe700 (LWP 14242)]
[New Thread 0x7fff81fff700 (LWP 14249)]
[New Thread 0x7fff817fe700 (LWP 14250)]
[New Thread 0x7fff80ffd700 (LWP 14251)]
[New Thread 0x7fff73fff700 (LWP 14252)]
[New Thread 0x7fff737fe700 (LWP 14253)]
[New Thread 0x7fff72ffd700 (LWP 14254)]
[New Thread 0x7fff727fc700 (LWP 14255)]
[New Thread 0x7fff71ffb700 (LWP 14256)]
[New Thread 0x7fff717fa700 (LWP 14257)]
[New Thread 0x7fff70ff9700 (LWP 14258)]
[New Thread 0x7fff63fff700 (LWP 14259)]
[New Thread 0x7fff637fe700 (LWP 14260)]
[New Thread 0x7fff62ffd700 (LWP 14261)]
[New Thread 0x7fff627fc700 (LWP 14262)]
[New Thread 0x7fff61ffb700 (LWP 14263)]

Thread 4 "openpose_ros_no" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc0209700 (LWP 14226)]
0x00007ffff5a71db1 in op::resizeFixedAspectRatio(cv::Mat const&, double, op::Point<int> const&, int, cv::Scalar_<double> const&) () from /home/cyril/Downloads/openpose/build/lib/libopenpose.so.1.0.1
(gdb)
```
Do you know how to solve that ?
Thanks!

**Comment by firephinx** [comment]
Can you check that your OpenCV and cv_bridge are working correctly by testing with the image converter example on http://wiki.ros.org/cv_bridge/Tutorials/UsingCvBridgeToConvertBetweenROSImagesAndOpenCVImages. 

If it works, can you see if the regular openpose_ros_node seg faults as well without using a launch file?

**Comment by varsha-sankar** [comment]
Without a launch file, the openpose_ros_node seg faults for me when I set the camera topic to a raw format (/camera/rgb/image_rect_color). However if I set to compressed format, there is no seg fault, but when I do an echo of the topic openpose/human_list, it doesn't display anything. Do you know what the reason could be?
