### ISSUE TITLE
New branch for ROS2 support

### ISSUE THREAD

**Issue by RemiRigal** [firephinx/openpose_ros#19]
Hello, thanks for the amazing work this package is really useful to me and done in a very efficient way.

I've migrated your code to be able to run with ROS2 (tested on eloquent), if you are interested can you create a new branch (`ros2` or `eloquent`) so that i can do a PR on it ?

If you want to have a look at it you can see the code [here](https://github.com/RemiRigal/openpose_ros/tree/ros2).

**Comment by firephinx** [comment]
Sounds good. Thanks for working on this. I created the ros2 branch so you can PR on it any time.

**Comment by RemiRigal** [comment]
Done with PR #20.
