### ISSUE TITLE
is there a way to use the pytorch models instead of the caffe ones ??

### ISSUE THREAD

**Issue by ymohamed08** [firephinx/openpose_ros#21]
i am trying to use the openPose model in https://github.com/Hzzone/pytorch-openpose, is there a way to do so easily ??

**Comment by firephinx** [comment]
It should be fairly straightforward. Just combine the demo.py code from the repository: https://github.com/Hzzone/pytorch-openpose/blob/master/demo.py
with code to subscribe to ROS images like this one: http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython

**Comment by ymohamed08** [comment]
thank you
